### PR TITLE
Remove all references to the CmuData.h file

### PR DESCRIPTION
**Pull request by jeffh1996**
Removed the CmuData.h file and all references to that file.

### CODE REVIEW

**Comment by jeffh1996** [comment]
The terms with "cmu" in `InternetReporting.cpp`, `SerialReporting.cpp`, and `SerialReportingTest.cpp` do not actually reference the removed `CmuData.h` file. They refer to items in the `BatteryData.h` and `BatteryFaultsData.h` files.

I did not want this PR to be very big so I did not change those. Since I cannot delete those "cmu" items without breaking the whole program, I plan to do a separate PR to change the items in the `BatteryData.h` and `BatteryFaultsData.h` and their dependent classes. 

If you want, I can fix those items, but that will require changing a lot of other things to ensure that the Test Tool will continue to function properly.

**Comment by enochtsang** [comment]
What kind of other references are there?

**Comment by jeffh1996** [comment]
There are a few member variables in `BatteryData.h` and `BatteryFaultsData.h` with "cmu" in their name (i.e: `cmu12VCurrentConsumption`, `lowestCellVoltageCmuNumber`, `cmuCanBusPowerStatus`, etc). This is why if you search for the term "cmu", references to those variables will pop up. 

There should be no references to any of the member variables in the `CmuData.h` file anymore.

**Comment by bill-luu** [comment]
If we're doing just `cmuData.h` that's fine, please make an issue to remove the rest of the CMU stuff then and we can address it in a later PR.

**Comment by jeffh1996** [comment]
Well, I'm also working on updating the `BatteryData.h` and BatteryFaultsData.h` protocol so these "cmu"s should be all gone when I'm done with that.

**Comment by enochtsang** [comment]
Yea, IMO the references that Jeffrey pointed out are totally valid to not be changed in this PR.

**Pull request merged**
