### PR TITLE
Epsilon-Telemetry-Test-Tool

### PR DESCRIPTION
**Pull request by shilpan97**
travis.yml file

### CODE REVIEW

**Comment by enochtsang** [comment]
Hey @shilpan97, please fix the build. Especially for a pull request that's about the build, it should be working haha xD

**Comment by shilpan97** [comment]
Should I just change this command: sudo apt-get -qq update to sudo apt-get update?

**Comment by bill-luu** [comment]
qq just hides the output so that it doesn't fill up the screen. That shouldn't be an issue

**Comment by bill-luu** [comment]
Next time, title the PR so that it's more descriptive of the changes made.
Other than that, lgtm! Go ahead and merge.

**Pull request merged**
